#!/usr/bin/env bash
# Signed + notarized macOS release build for Petomato.
#
# Prereqs (one-time):
#   1. Apple Developer Program membership (paid).
#   2. A "Developer ID Application" certificate installed in your login keychain.
#      Verify:  security find-identity -v | grep "Developer ID Application"
#   3. Notarization credentials (either an app-specific password OR an App Store
#      Connect API key) — see the env vars below.
#
# Usage:
#   export APPLE_SIGNING_IDENTITY="Developer ID Application: Your Name (TEAMID)"
#   # --- option A: app-specific password ---
#   export APPLE_ID="you@example.com"
#   export APPLE_PASSWORD="xxxx-xxxx-xxxx-xxxx"   # app-specific password from appleid.apple.com
#   export APPLE_TEAM_ID="TEAMID"
#   # --- option B: App Store Connect API key (instead of A) ---
#   # export APPLE_API_ISSUER="...-...-...-...-..."
#   # export APPLE_API_KEY="ABCDE12345"
#   # export APPLE_API_KEY_PATH="/path/to/AuthKey_ABCDE12345.p8"
#
#   ./scripts/release-mac.sh           # builds universal + aarch64, signs, notarizes, staples
set -euo pipefail
cd "$(dirname "$0")/.."

: "${APPLE_SIGNING_IDENTITY:?Set APPLE_SIGNING_IDENTITY (Developer ID Application: Name (TEAMID))}"
if [[ -z "${APPLE_API_KEY:-}" && -z "${APPLE_ID:-}" ]]; then
  echo "Set either APPLE_API_* (API key) or APPLE_ID/APPLE_PASSWORD/APPLE_TEAM_ID (app-specific password)." >&2
  exit 1
fi

# Updater signing — required so `createUpdaterArtifacts` produces a valid
# `.app.tar.gz.sig`. Defaults to the key generated by `tauri signer generate`.
# Must correspond to the pubkey embedded in tauri.conf.json.
export TAURI_SIGNING_PRIVATE_KEY="${TAURI_SIGNING_PRIVATE_KEY:-$HOME/.tauri/petomato-updater.key}"
export TAURI_SIGNING_PRIVATE_KEY_PASSWORD="${TAURI_SIGNING_PRIVATE_KEY_PASSWORD:-}"
if [[ ! -f "$TAURI_SIGNING_PRIVATE_KEY" && ${#TAURI_SIGNING_PRIVATE_KEY} -lt 200 ]]; then
  echo "Updater signing key not found at $TAURI_SIGNING_PRIVATE_KEY" >&2
  echo "Generate one:  pnpm tauri signer generate -w ~/.tauri/petomato-updater.key" >&2
  exit 1
fi

echo "==> Signing identity: $APPLE_SIGNING_IDENTITY"
echo "==> Building + signing + notarizing (universal)…"
pnpm tauri build --target universal-apple-darwin

UNI="src-tauri/target/universal-apple-darwin/release/bundle/dmg"
MAC="src-tauri/target/universal-apple-darwin/release/bundle/macos"
echo "==> Verifying notarization staple…"
for dmg in "$UNI"/*.dmg; do
  echo "--- $dmg"
  xcrun stapler validate "$dmg" || echo "    (not stapled — check notarization log)"
  spctl -a -t open --context context:primary-signature -v "$dmg" 2>&1 | head -2 || true
done

# Build latest.json (the manifest the in-app updater fetches). The universal
# .app.tar.gz serves both Apple Silicon and Intel.
VERSION="$(node -p "require('./package.json').version")"
TARBALL="$(ls "$MAC"/*.app.tar.gz 2>/dev/null | head -1 || true)"
SIG_FILE="$TARBALL.sig"
if [[ -n "$TARBALL" && -f "$SIG_FILE" ]]; then
  SIG="$(cat "$SIG_FILE")"
  URL="https://github.com/Reneuwumuhire/petomato/releases/download/v$VERSION/$(basename "$TARBALL")"
  PUB_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  OUT="src-tauri/target/universal-apple-darwin/release/bundle/latest.json"
  node -e '
    const fs=require("fs");
    const [version,sig,url,pubDate]=process.argv.slice(1);
    const platforms={};
    for (const k of ["darwin-aarch64","darwin-x86_64"]) platforms[k]={signature:sig,url};
    fs.writeFileSync(process.env.OUT, JSON.stringify({version,notes:"See the GitHub release notes.",pub_date:pubDate,platforms},null,2));
  ' "$VERSION" "$SIG" "$URL" "$PUB_DATE"
  echo "==> Wrote $OUT (macOS-only)."
  echo "    Upload to the v$VERSION release:  $(basename "$TARBALL"), its .sig, the DMG, and latest.json"
  echo "    e.g.  gh release upload v$VERSION \"$TARBALL\" \"$SIG_FILE\" \"$UNI\"/*.dmg \"$OUT\" --clobber"
else
  echo "WARNING: no .app.tar.gz(.sig) found — is createUpdaterArtifacts enabled and the signing key set?" >&2
fi
echo "==> Done. DMG signed + notarized; updater manifest ready."
echo "    NOTE: this builds macOS only. For a cross-platform release (mac+Windows)"
echo "    with auto-generated latest.json, push a tag and let CI do it:  ./scripts/release.sh $VERSION"
